# Generated by Django 4.0.2 on 2022-03-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carros',
            old_name='ano',
            new_name='Ano',
        ),
    ]
